apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: auth-service
  labels:
    app: welhome
    micro-service: auth
  namespace: ns-welhome
spec:
  # Choose how to expose your service
  type: LoadBalancer
  ports:
    # The port number to expose the service
    - port: 9999 
      targetPort: 9999  # Pod to route service traffic  
  selector:
    app: welhome
    micro-service: auth
