apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: database-service
  labels:
    app: database-service
  namespace: ns-welhome
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - port: 9090
      nodePort: 30002
  # Pod to route service traffic  
  selector:
    app: database-service