apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ns-welhome
data:
  application.properties: |
    databaseService.url=http://database-service:9090/api
    cors.allowedOrigins=https://welhome.minhviet.cc
    authenticationService.url=https://kube.minhviet.cc/auth
