apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: backend
  labels:
    app: welhome
    micro-service: backend 
  namespace: ns-welhome
spec:
  # Choose how to expose your service
  type: ClusterIP
  ports:
    # The port number to expose the service
    - port: 8080
      protocol: TCP
  # Pod to route service traffic  
  selector:
    app: welhome
    micro-service: backend 
