apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgresdb
  labels:
    app: welhome
    micro-service: postgresdb
  namespace: ns-welhome
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - port: 5432
      nodePort: 30001
  # Pod to route service traffic  
  selector:
    app: welhome
    micro-service: postgresdb
